version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  gosec:
    severity: "medium"
    confidence: "medium"

linters:
  disable:
    - revive
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - revive
